DEBUG = True
use_reloader=True
SQLALCHEMY_DATABASE_URI = 'mysql://william:j2554fci@pits.minivps.info/pitsdb'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'chave secreta do pits.med.br'
CSRF_ENABLE = True
CSRF_SESSION_KEY = "secret"
WTF_CSRF_ENABLED = True
WTF_CSRF_SECRET_KEY = 'a random string'
WTF_CSRF_TIME_LIMIT = 10000
USER_ENABLE_EMAIL = False
USER_ENABLE_REGISTRATION = False
''' USER_REGISTER_TEMPLATE  = 'flask_user/register' '''
''' 'USER_LOGIN_TEMPLATE = 'flask_user/login.html'  '''
USER_ENABLE_USERNAME = True
USER_PASSWORD_HASH = 'bcrypt'
USER_PASSWORD_HASH_MODE = 'passlib'
USER_PASSWORD_SALT = 'dfadasdasljdnasjdnasjldnalsjdn'
USER_ENABLE_LOGIN_WITHOUT_CONFIRM_EMAIL = True
BABEL_DEFAULT_LOCALE = 'pt'
BABEL_DEFAULT_TIMEZONE = 'Brazil/East'
USER_APP_NAME = 'Pits'
USER_LOGOUT_URL = '/user/logout'
USER_CHANGE_PASSWORD_URL = '/user/change-password'
USER_FORGOT_PASSWORD_URL = '/user/forgot-password'
USER_RESET_PASSWORD_URL = '/user/reset-password/<token>'
USER_ENABLE_FORGOT_PASSWORD = True
